-- Reps Club · Fase 0 · Carga do catálogo base de exercícios
--
-- Gerado de handoff_claude_code/data/exercicios.json (117 exercícios).
-- Idempotente: `on conflict (name) do nothing` — rodar de novo não duplica.
-- O catálogo é global e sem dono; escrita pela API fica bloqueada pelo RLS.

insert into public.exercises_catalog (name,muscle_group,equipment,is_bodyweight,is_unilateral,default_rest_seconds) values
('Supino reto com barra','peito','barra',false,false,120),
('Supino inclinado com barra','peito','barra',false,false,120),
('Supino declinado com barra','peito','barra',false,false,120),
('Supino reto com halteres','peito','halter',false,false,90),
('Supino inclinado com halteres','peito','halter',false,false,90),
('Crucifixo reto com halteres','peito','halter',false,false,75),
('Crucifixo inclinado com halteres','peito','halter',false,false,75),
('Crossover no cabo','peito','cabo',false,false,60),
('Crucifixo na máquina (voador)','peito','maquina',false,false,60),
('Supino na máquina articulada','peito','maquina',false,false,90),
('Flexão de braço','peito','peso_corporal',true,false,60),
('Flexão de braço inclinada','peito','peso_corporal',true,false,60),
('Paralelas com foco em peito','peito','peso_corporal',true,false,90),
('Pullover com halter','peito','halter',false,false,75),
('Barra fixa pronada','costas','peso_corporal',true,false,120),
('Barra fixa supinada','costas','peso_corporal',true,false,120),
('Puxada frontal na barra guiada','costas','maquina',false,false,90),
('Puxada frontal com pegada neutra','costas','maquina',false,false,90),
('Puxada articulada unilateral','costas','maquina',false,true,75),
('Remada curvada com barra','costas','barra',false,false,120),
('Remada curvada com pegada supinada','costas','barra',false,false,120),
('Remada unilateral com halter','costas','halter',false,true,75),
('Remada baixa no cabo','costas','cabo',false,false,90),
('Remada cavalinho (T-bar)','costas','barra',false,false,105),
('Remada na máquina sentado','costas','maquina',false,false,90),
('Pulldown com corda','costas','cabo',false,false,60),
('Levantamento terra','costas','barra',false,false,180),
('Levantamento terra sumô','costas','barra',false,false,180),
('Pull-over no cabo','costas','cabo',false,false,60),
('Remada invertida na barra','costas','peso_corporal',true,false,75),
('Desenvolvimento com barra','ombros','barra',false,false,120),
('Desenvolvimento com halteres','ombros','halter',false,false,90),
('Desenvolvimento Arnold','ombros','halter',false,false,90),
('Desenvolvimento na máquina','ombros','maquina',false,false,90),
('Elevação lateral com halteres','ombros','halter',false,false,60),
('Elevação lateral no cabo','ombros','cabo',false,true,60),
('Elevação lateral na máquina','ombros','maquina',false,false,60),
('Elevação frontal com halteres','ombros','halter',false,false,60),
('Elevação frontal com anilha','ombros','anilha',false,false,60),
('Crucifixo inverso com halteres','ombros','halter',false,false,60),
('Crucifixo inverso na máquina','ombros','maquina',false,false,60),
('Face pull na corda','ombros','cabo',false,false,60),
('Desenvolvimento militar em pé','ombros','barra',false,false,120),
('Encolhimento com barra','trapezio','barra',false,false,75),
('Encolhimento com halteres','trapezio','halter',false,false,75),
('Remada alta com barra','trapezio','barra',false,false,90),
('Rosca direta com barra','biceps','barra',false,false,75),
('Rosca direta com barra W','biceps','barra',false,false,75),
('Rosca alternada com halteres','biceps','halter',false,true,60),
('Rosca simultânea com halteres','biceps','halter',false,false,60),
('Rosca martelo','biceps','halter',false,false,60),
('Rosca concentrada','biceps','halter',false,true,60),
('Rosca Scott','biceps','barra',false,false,75),
('Rosca no cabo','biceps','cabo',false,false,60),
('Rosca inclinada com halteres','biceps','halter',false,false,60),
('Rosca 21','biceps','barra',false,false,90),
('Tríceps testa com barra','triceps','barra',false,false,75),
('Tríceps francês com halter','triceps','halter',false,false,75),
('Tríceps na polia com barra','triceps','cabo',false,false,60),
('Tríceps na polia com corda','triceps','cabo',false,false,60),
('Tríceps coice com halter','triceps','halter',false,true,60),
('Tríceps banco','triceps','peso_corporal',true,false,60),
('Paralelas','triceps','peso_corporal',true,false,90),
('Supino fechado','triceps','barra',false,false,105),
('Tríceps na máquina','triceps','maquina',false,false,60),
('Rosca de punho com barra','antebraco','barra',false,false,45),
('Rosca de punho inversa','antebraco','barra',false,false,45),
('Pegada de força (farmer walk)','antebraco','halter',false,false,90),
('Agachamento livre com barra','quadriceps','barra',false,false,180),
('Agachamento frontal','quadriceps','barra',false,false,150),
('Agachamento no Smith','quadriceps','smith',false,false,120),
('Agachamento búlgaro','quadriceps','halter',false,true,90),
('Leg press 45°','quadriceps','maquina',false,false,120),
('Leg press horizontal','quadriceps','maquina',false,false,120),
('Cadeira extensora','quadriceps','maquina',false,false,75),
('Afundo com halteres','quadriceps','halter',false,true,90),
('Passada com barra','quadriceps','barra',false,true,105),
('Agachamento hack','quadriceps','maquina',false,false,120),
('Agachamento sumô com halter','quadriceps','halter',false,false,105),
('Step-up no banco','quadriceps','halter',false,true,75),
('Agachamento livre sem peso','quadriceps','peso_corporal',true,false,60),
('Mesa flexora','posterior','maquina',false,false,75),
('Cadeira flexora','posterior','maquina',false,false,75),
('Flexora unilateral em pé','posterior','maquina',false,true,60),
('Stiff com barra','posterior','barra',false,false,120),
('Stiff com halteres','posterior','halter',false,false,105),
('Levantamento terra romeno unilateral','posterior','halter',false,true,90),
('Bom dia com barra','posterior','barra',false,false,105),
('Nórdico','posterior','peso_corporal',true,false,90),
('Elevação pélvica com barra','gluteos','barra',false,false,105),
('Elevação pélvica na máquina','gluteos','maquina',false,false,90),
('Coice no cabo','gluteos','cabo',false,true,60),
('Abdução na máquina','gluteos','maquina',false,false,60),
('Abdução com elástico','gluteos','elastico',false,false,45),
('Ponte de glúteo','gluteos','peso_corporal',true,false,60),
('Panturrilha em pé na máquina','panturrilha','maquina',false,false,60),
('Panturrilha sentado','panturrilha','maquina',false,false,60),
('Panturrilha no leg press','panturrilha','maquina',false,false,60),
('Panturrilha unilateral com halter','panturrilha','halter',false,true,45),
('Abdominal supra no solo','abdomen','peso_corporal',true,false,45),
('Abdominal infra na barra','abdomen','peso_corporal',true,false,60),
('Abdominal na máquina','abdomen','maquina',false,false,60),
('Abdominal no cabo (rosca)','abdomen','cabo',false,false,60),
('Prancha isométrica','abdomen','peso_corporal',true,false,45),
('Prancha lateral','abdomen','peso_corporal',true,true,45),
('Elevação de pernas suspenso','abdomen','peso_corporal',true,false,60),
('Rotação russa com anilha','abdomen','anilha',false,false,45),
('Ab wheel','abdomen','peso_corporal',true,false,60),
('Hiperextensão lombar','lombar','maquina',false,false,75),
('Extensão lombar no banco romano','lombar','peso_corporal',true,false,75),
('Esteira - caminhada inclinada','cardio','cardio',true,false,0),
('Esteira - corrida','cardio','cardio',true,false,0),
('Bicicleta ergométrica','cardio','cardio',true,false,0),
('Elíptico','cardio','cardio',true,false,0),
('Escada (stair climber)','cardio','cardio',true,false,0),
('Remo ergômetro','cardio','cardio',true,false,0),
('Pular corda','cardio','peso_corporal',true,false,60)
on conflict (name) do nothing;
