-- Reps Club · Vídeo de demonstração no catálogo (pedido do Otávio, 09/10) — parte 1
--
-- Um link do YouTube por exercício do catálogo, para o "Como fazer" do aluno
-- (0038). Conteúdo do catálogo vem por migration (decisão de 27/09): não há
-- policy de escrita no catálogo pela API.
--
-- Como os links foram escolhidos: busca por "<nome do exercício> como fazer"
-- restrita ao YouTube, e o primeiro vídeo de demonstração cujo título casa com
-- o exercício, de preferência em português. Onde não havia vídeo em português,
-- entrou um em inglês ou espanhol. Daqui o YouTube não abre (a rede da sessão
-- bloqueia), então o vídeo foi escolhido pelo título, não assistido.
--
-- Casa pelo NOME, não pelo id: o catálogo é semeado e o nome é único nele, e
-- id gerado não se escreve em migration. Idempotente: rodar de novo regrava o
-- mesmo link.
--
-- Esta parte cobre 197 dos 501. Os 19 exercícios que já estavam em algum
-- treino vieram primeiro. Os outros ficam para a parte 2.

update public.exercises_catalog c set video_url = v.url
from (values
  ('Rosca alternada com halteres', 'https://www.youtube.com/watch?v=865ar4KPodA'),
  ('Barra fixa supinada', 'https://www.youtube.com/watch?v=oNSMi4d6O0M'),
  ('Levantamento terra', 'https://www.youtube.com/watch?v=QiqUXcz2iyA'),
  ('Levantamento terra sumô', 'https://www.youtube.com/watch?v=F1aY4AIim_E'),
  ('Pull-over no cabo', 'https://www.youtube.com/watch?v=teTtaiZG4rM'),
  ('Pulldown com corda', 'https://www.youtube.com/watch?v=e9XbR9Hvm4c'),
  ('Puxada frontal com pegada neutra', 'https://www.youtube.com/watch?v=jv04AKHErDA'),
  ('Remada cavalinho (T-bar)', 'https://www.youtube.com/watch?v=9SH7hdDYQ7w'),
  ('Remada na máquina sentado', 'https://www.youtube.com/watch?v=WerTQoDj-_g'),
  ('Face pull na corda', 'https://www.youtube.com/watch?v=YxQivR_kljk'),
  ('Crossover no cabo', 'https://www.youtube.com/watch?v=ifwx2iuv4kA'),
  ('Crucifixo inclinado com halteres', 'https://www.youtube.com/watch?v=oQARSPqhvs8'),
  ('Crucifixo reto com halteres', 'https://www.youtube.com/watch?v=fG2fUgin3Zw'),
  ('Flexão de braço', 'https://www.youtube.com/watch?v=xgqFpfoQEEs'),
  ('Pullover com halter', 'https://www.youtube.com/watch?v=TVUYI8UhahE'),
  ('Cadeira flexora', 'https://www.youtube.com/watch?v=CHsaztLSSrc'),
  ('Agachamento hack', 'https://www.youtube.com/watch?v=gEYYCvNI6hI'),
  ('Supino fechado', 'https://www.youtube.com/watch?v=sYaoxGgOdCU'),
  ('Tríceps coice com halter', 'https://www.youtube.com/watch?v=99gVAsqhZXY'),
  ('Ab wheel', 'https://www.youtube.com/watch?v=bq1KTUj3ae0'),
  ('Abdominal infra na barra', 'https://www.youtube.com/watch?v=8uqCv5MIHjI'),
  ('Abdominal na máquina', 'https://www.youtube.com/watch?v=pR7WtwTOOTw'),
  ('Abdominal no cabo (rosca)', 'https://www.youtube.com/watch?v=eB-LUPltCfM'),
  ('Abdominal supra no solo', 'https://www.youtube.com/watch?v=fhGI76QdK2A'),
  ('Elevação de pernas suspenso', 'https://www.youtube.com/watch?v=Qg5KwPlB75E'),
  ('Prancha isométrica', 'https://www.youtube.com/watch?v=OnVIGDpnMow'),
  ('Prancha lateral', 'https://www.youtube.com/watch?v=zt7PjySXWCw'),
  ('Rotação russa com anilha', 'https://www.youtube.com/watch?v=GHPI80YS2Ns'),
  ('Pegada de força (farmer walk)', 'https://www.youtube.com/watch?v=VZ-E-YYbYEg'),
  ('Rosca de punho com barra', 'https://www.youtube.com/watch?v=9w7XMvLM3qo'),
  ('Rosca de punho inversa', 'https://www.youtube.com/watch?v=xVRGEOFv0x8'),
  ('Chin-up pegada fechada', 'https://www.youtube.com/watch?v=lohgPjOEL7M'),
  ('Rosca 21', 'https://www.youtube.com/watch?v=T6ic2jxFNQg'),
  ('Rosca 21 com halteres', 'https://www.youtube.com/watch?v=VFeFD7fbDDw'),
  ('Rosca Scott', 'https://www.youtube.com/watch?v=FxrrSYi9nks'),
  ('Rosca Scott com barra W', 'https://www.youtube.com/watch?v=AR4-VOUnPRc'),
  ('Rosca Scott inversa', 'https://www.youtube.com/watch?v=Lv6HaEyg8w0'),
  ('Rosca Scott na máquina', 'https://www.youtube.com/watch?v=90sG3CFTz4E'),
  ('Rosca Scott no cabo', 'https://www.youtube.com/watch?v=xct7NL837Uc'),
  ('Rosca Scott unilateral com halter', 'https://www.youtube.com/watch?v=IFZ9be8iUVg'),
  ('Rosca Zottman', 'https://www.youtube.com/watch?v=x8eZaW-bZOE'),
  ('Rosca alternada sentado', 'https://www.youtube.com/watch?v=DXMvVIYZYww'),
  ('Rosca bayesiana no cabo', 'https://www.youtube.com/watch?v=f0Cwx0ezuHU'),
  ('Rosca com elástico', 'https://www.youtube.com/watch?v=pwv9fFtmC_0'),
  ('Rosca concentrada', 'https://www.youtube.com/watch?v=NftBaXxrLJ4'),
  ('Rosca concentrada em pé', 'https://www.youtube.com/watch?v=xnh2qIV7DeM'),
  ('Rosca concentrada no cabo', 'https://www.youtube.com/watch?v=Zd-9K3HjScE'),
  ('Rosca deitado no cabo', 'https://www.youtube.com/watch?v=5kjoCPNdXzE'),
  ('Rosca direta com barra', 'https://www.youtube.com/watch?v=Et1wgGMGW8w'),
  ('Rosca direta com barra W', 'https://www.youtube.com/watch?v=V6UEDzY51gY'),
  ('Rosca direta no cabo em pé com barra reta', 'https://www.youtube.com/watch?v=I81otxUG8ME'),
  ('Rosca direta pegada aberta', 'https://www.youtube.com/watch?v=n158HS07tOE'),
  ('Rosca direta pegada fechada', 'https://www.youtube.com/watch?v=RuQoMKgqW7U'),
  ('Rosca drag', 'https://www.youtube.com/watch?v=PYh6Xxmgl2E'),
  ('Rosca duplo bíceps no cabo', 'https://www.youtube.com/watch?v=owR_1o-YX4g'),
  ('Rosca inclinada alternada', 'https://www.youtube.com/watch?v=mUEDnCGrNP4'),
  ('Rosca inclinada com halteres', 'https://www.youtube.com/watch?v=tiWfdwgbrBQ'),
  ('Rosca inversa com barra', 'https://www.youtube.com/watch?v=xuZbpjvKnUk'),
  ('Rosca inversa com barra W', 'https://www.youtube.com/watch?v=xJjkMqMd7yk'),
  ('Rosca martelo', 'https://www.youtube.com/watch?v=ZiasEcCg0wg'),
  ('Rosca martelo alternada', 'https://www.youtube.com/watch?v=xvvjkh3Aa4s'),
  ('Rosca martelo com barra romana', 'https://www.youtube.com/watch?v=4IoD36CrxlI'),
  ('Rosca martelo com corda', 'https://www.youtube.com/watch?v=x2aTCnpMwVk'),
  ('Rosca martelo cruzada', 'https://www.youtube.com/watch?v=jgqnyo-TopU'),
  ('Rosca martelo inclinada', 'https://www.youtube.com/watch?v=GRVPkgASStk'),
  ('Rosca martelo no banco Scott', 'https://www.youtube.com/watch?v=X-eaAUy579I'),
  ('Rosca martelo sentado', 'https://www.youtube.com/watch?v=zJgwwvS2pBc'),
  ('Rosca na máquina', 'https://www.youtube.com/watch?v=AaHuhXKH8U8'),
  ('Rosca no TRX', 'https://www.youtube.com/watch?v=BaaAUc1w1lc'),
  ('Rosca no cabo', 'https://www.youtube.com/watch?v=X12n32mNBp8'),
  ('Rosca no cabo com barra W', 'https://www.youtube.com/watch?v=w1oEjoNL090'),
  ('Rosca no cabo com corda', 'https://www.youtube.com/watch?v=anDf4NiAaDg'),
  ('Rosca simultânea com halteres', 'https://www.youtube.com/watch?v=G3F-nJglpBo'),
  ('Rosca simultânea sentado', 'https://www.youtube.com/watch?v=FIRjtk3ehzU'),
  ('Rosca spider com barra', 'https://www.youtube.com/watch?v=twd5nb3ciX0'),
  ('Rosca spider com halteres', 'https://www.youtube.com/watch?v=NFILNmHcdl0'),
  ('Rosca unilateral na máquina', 'https://www.youtube.com/watch?v=LGUX2hiumXE'),
  ('Rosca unilateral no cabo', 'https://www.youtube.com/watch?v=peXvZFPfh4U'),
  ('Bicicleta ergométrica', 'https://www.youtube.com/watch?v=_NyqsWSkOKc'),
  ('Elíptico', 'https://www.youtube.com/watch?v=Rltlu55sBLE'),
  ('Escada (stair climber)', 'https://www.youtube.com/watch?v=nal_FtVy8yk'),
  ('Esteira - caminhada inclinada', 'https://www.youtube.com/watch?v=FIQuECwhIYo'),
  ('Esteira - corrida', 'https://www.youtube.com/watch?v=9OCjXQNRXg4'),
  ('Pular corda', 'https://www.youtube.com/watch?v=bB2BMeZTygg'),
  ('Remo ergômetro', 'https://www.youtube.com/watch?v=oDtV66s1wQM'),
  ('Barra fixa assistida na máquina', 'https://www.youtube.com/watch?v=yoGQNEHGlak'),
  ('Barra fixa com carga', 'https://www.youtube.com/watch?v=gCyR7yYgAYo'),
  ('Barra fixa com elástico', 'https://www.youtube.com/watch?v=zSuNm2EVaL8'),
  ('Barra fixa negativa', 'https://www.youtube.com/watch?v=r1v7PxcZbaY'),
  ('Barra fixa pegada aberta', 'https://www.youtube.com/watch?v=MK9U7gKs-0E'),
  ('Barra fixa pegada neutra', 'https://www.youtube.com/watch?v=pmDEhjDUQeA'),
  ('Barra fixa pronada', 'https://www.youtube.com/watch?v=_wH1BwSL_qg'),
  ('Levantamento terra com déficit', 'https://www.youtube.com/watch?v=AKDUEYk4FHM'),
  ('Levantamento terra com halteres', 'https://www.youtube.com/watch?v=orEEpxzVUuI'),
  ('Levantamento terra com pausa', 'https://www.youtube.com/watch?v=cjT5Fx4qv-4'),
  ('Levantamento terra com trap bar', 'https://www.youtube.com/watch?v=igVOBayXWBE'),
  ('Levantamento terra snatch grip', 'https://www.youtube.com/watch?v=GP6VNoIZyF4'),
  ('Pulldown com barra reta', 'https://www.youtube.com/watch?v=-74jtRco5kI'),
  ('Pulldown unilateral', 'https://www.youtube.com/watch?v=YNDcE23PRdA'),
  ('Pullover na polia com corda', 'https://www.youtube.com/watch?v=lChEuE0wH3w'),
  ('Puxada alta na máquina articulada', 'https://www.youtube.com/watch?v=xSSle0N-364'),
  ('Puxada alta unilateral na máquina', 'https://www.youtube.com/watch?v=LtrLk1yHMhw'),
  ('Puxada articulada unilateral', 'https://www.youtube.com/watch?v=lSRiSmkEAs8'),
  ('Puxada atrás da nuca', 'https://www.youtube.com/watch?v=Y09q8JO0IwM'),
  ('Puxada com corda (high row)', 'https://www.youtube.com/watch?v=gyNOCnGVa_k'),
  ('Puxada frontal com triângulo', 'https://www.youtube.com/watch?v=WBqGN2Po9Z8'),
  ('Puxada frontal pegada aberta no cabo', 'https://www.youtube.com/watch?v=BOW9my4J_ek'),
  ('Puxada frontal pegada neutra aberta', 'https://www.youtube.com/watch?v=J-xicyp4M9c'),
  ('Puxada frontal pegada supinada', 'https://www.youtube.com/watch?v=SRh5HbCouE0'),
  ('Puxada frontal unilateral na máquina', 'https://www.youtube.com/watch?v=CqHwcDAvWi0'),
  ('Puxada unilateral ajoelhado', 'https://www.youtube.com/watch?v=p2R58fG10pU'),
  ('Puxada unilateral no cabo', 'https://www.youtube.com/watch?v=9tXa0ZZIjCQ'),
  ('Remada Meadows', 'https://www.youtube.com/watch?v=dvsreO9mY7g'),
  ('Remada Pendlay', 'https://www.youtube.com/watch?v=NXuQZln3xGg'),
  ('Remada articulada pegada aberta', 'https://www.youtube.com/watch?v=xpkNxVSN2ec'),
  ('Remada articulada unilateral', 'https://www.youtube.com/watch?v=Prevu525iYQ'),
  ('Remada baixa com corda', 'https://www.youtube.com/watch?v=poRq3EcP2oo'),
  ('Remada baixa no cabo', 'https://www.youtube.com/watch?v=2YebbYuuBJQ'),
  ('Remada baixa pegada aberta', 'https://www.youtube.com/watch?v=uEytT5-Wrxk'),
  ('Remada baixa pegada supinada', 'https://www.youtube.com/watch?v=UmNyYKOhwS8'),
  ('Remada baixa unilateral', 'https://www.youtube.com/watch?v=J4a5-GBIp2s'),
  ('Remada cavalinho com apoio de peito', 'https://www.youtube.com/watch?v=1irSxCGkkpY'),
  ('Remada cavalinho pegada neutra', 'https://www.youtube.com/watch?v=cVVTvhULl6E'),
  ('Remada com elástico', 'https://www.youtube.com/watch?v=j9KCjIBCG8k'),
  ('Remada com kettlebell', 'https://www.youtube.com/watch?v=v44PN8KhMrQ'),
  ('Remada com peito apoiado com halteres', 'https://www.youtube.com/watch?v=B0XfdJh_kJg'),
  ('Remada curvada com barra', 'https://www.youtube.com/watch?v=s4jeKLRghTM'),
  ('Remada curvada com halteres', 'https://www.youtube.com/watch?v=cCpzwQnWTdU'),
  ('Remada curvada com pegada supinada', 'https://www.youtube.com/watch?v=0BfB6WHRks8'),
  ('Remada curvada unilateral com halter no banco', 'https://www.youtube.com/watch?v=UBTxmzIiRiQ'),
  ('Remada invertida na barra', 'https://www.youtube.com/watch?v=UYSAjUGcZLg'),
  ('Remada invertida no TRX', 'https://www.youtube.com/watch?v=v_OlSx9cwIY'),
  ('Remada invertida pegada supinada', 'https://www.youtube.com/watch?v=ymvbaQzGmnQ'),
  ('Remada landmine', 'https://www.youtube.com/watch?v=C9gEMHhz4H0'),
  ('Remada na máquina articulada', 'https://www.youtube.com/watch?v=G_2iVSV465w'),
  ('Remada no Smith', 'https://www.youtube.com/watch?v=YBbuote_idg'),
  ('Remada serrote', 'https://www.youtube.com/watch?v=K25eTWoEOWU'),
  ('Remada unilateral com halter', 'https://www.youtube.com/watch?v=WrF-rpwax4k'),
  ('Remada unilateral no banco inclinado', 'https://www.youtube.com/watch?v=EzlZRKPVsag'),
  ('Remada renegada', 'https://www.youtube.com/watch?v=njelWrWK0fE'),
  ('Remada seal com barra', 'https://www.youtube.com/watch?v=w9SGH9u86Tg'),
  ('Remada unilateral no cabo em pé', 'https://www.youtube.com/watch?v=-oKoLS9bDhg'),
  ('Abdução com caneleira deitado', 'https://www.youtube.com/watch?v=IVRY84eMDMk'),
  ('Abdução com elástico', 'https://www.youtube.com/watch?v=HMfy4DcNQqc'),
  ('Abdução com elástico sentado', 'https://www.youtube.com/watch?v=lXwHawfezYU'),
  ('Abdução deitado lateral', 'https://www.youtube.com/watch?v=hFm1YN0MMoM'),
  ('Abdução em pé na máquina', 'https://www.youtube.com/watch?v=Xo-PhNDaBJE'),
  ('Abdução na máquina', 'https://www.youtube.com/watch?v=50qHGus1TZk'),
  ('Abdução na máquina com tronco inclinado', 'https://www.youtube.com/watch?v=yarjFjsNtJk'),
  ('Abdução no cabo', 'https://www.youtube.com/watch?v=4MbY6NmLP_c'),
  ('Afundo cruzado (curtsy lunge)', 'https://www.youtube.com/watch?v=I2Y1haTqM8k'),
  ('Agachamento búlgaro com tronco inclinado', 'https://www.youtube.com/watch?v=eZOgPHJ0sPI'),
  ('Agachamento sumô com barra', 'https://www.youtube.com/watch?v=Bclssc88Xjs'),
  ('Agachamento sumô com kettlebell', 'https://www.youtube.com/watch?v=7CTbrHuL_b4'),
  ('Caminhada lateral com elástico', 'https://www.youtube.com/watch?v=2z5sw4TbeMA'),
  ('Clamshell com elástico', 'https://www.youtube.com/watch?v=irUL2V47cIo'),
  ('Coice com caneleira (quatro apoios)', 'https://www.youtube.com/watch?v=RqGQZMusai4'),
  ('Coice com elástico', 'https://www.youtube.com/watch?v=p5NbsTL09o0'),
  ('Coice na máquina', 'https://www.youtube.com/watch?v=lJqJvUXuVyc'),
  ('Coice no cabo', 'https://www.youtube.com/watch?v=KoGf9T179Vg'),
  ('Coice na polia em pé com perna estendida', 'https://www.youtube.com/watch?v=uNqFzaH46ag'),
  ('Elevação pélvica com barra', 'https://www.youtube.com/watch?v=5KYtuo5Y-sg'),
  ('Elevação pélvica com elástico', 'https://www.youtube.com/watch?v=NRohLqmwETI'),
  ('Elevação pélvica com halter', 'https://www.youtube.com/watch?v=ECbv51lHtq4'),
  ('Elevação pélvica com kettlebell', 'https://www.youtube.com/watch?v=g657Pw9lyGI'),
  ('Elevação pélvica com pausa', 'https://www.youtube.com/watch?v=wtBTk1KylcE'),
  ('Elevação pélvica com pés elevados', 'https://www.youtube.com/watch?v=a6EzrTTmPjI'),
  ('Elevação pélvica na máquina', 'https://www.youtube.com/watch?v=WniGjvJlSx4'),
  ('Elevação pélvica no Smith', 'https://www.youtube.com/watch?v=0I3xQYtPCGQ'),
  ('Elevação pélvica unilateral', 'https://www.youtube.com/watch?v=4AeXJJRhkMw'),
  ('Elevação pélvica unilateral com halter', 'https://www.youtube.com/watch?v=jYTWLQ7FAkk'),
  ('Extensão de quadril no banco romano', 'https://www.youtube.com/watch?v=J_9pG2Yyh74'),
  ('Extensão reversa (reverse hyper)', 'https://www.youtube.com/watch?v=Pqigpd54aL8'),
  ('Fire hydrant', 'https://www.youtube.com/watch?v=W2PNcNCfIF4'),
  ('Fire hydrant com elástico', 'https://www.youtube.com/shorts/7xYCn7Z7Y44'),
  ('Frog pump', 'https://www.youtube.com/watch?v=x0cC09aPeq0'),
  ('Kickback no cabo ajoelhado', 'https://www.youtube.com/watch?v=xFTHo2Xd2n0'),
  ('Ponte de glúteo', 'https://www.youtube.com/watch?v=MmmgKMkT2A0'),
  ('Ponte de glúteo com barra', 'https://www.youtube.com/watch?v=3SNS4Y1wN8Y'),
  ('Ponte de glúteo com elástico', 'https://www.youtube.com/watch?v=q5U-p6vA3uo'),
  ('Ponte de glúteo com halter', 'https://www.youtube.com/watch?v=DWY10gV95NY'),
  ('Ponte de glúteo com marcha', 'https://www.youtube.com/watch?v=1OBHq-GPuk0'),
  ('Ponte de glúteo com pés na bola', 'https://www.youtube.com/watch?v=bpjGPzdU3Tg'),
  ('Ponte de glúteo unilateral', 'https://www.youtube.com/watch?v=qAYFKJsnqEM'),
  ('Pull-through com elástico', 'https://www.youtube.com/watch?v=mm7v2-cnoR0'),
  ('Step-up alto', 'https://www.youtube.com/watch?v=eybILuxUfEU'),
  ('Extensão lombar no banco romano', 'https://www.youtube.com/watch?v=hfFVbXJ5UvQ'),
  ('Hiperextensão lombar', 'https://www.youtube.com/watch?v=R-XcbVbMJF0'),
  ('Crucifixo inverso com elástico', 'https://www.youtube.com/watch?v=V2Vo0UIlFEE'),
  ('Crucifixo inverso com halteres', 'https://www.youtube.com/watch?v=oOhqtQN4g0o'),
  ('Crucifixo inverso na máquina', 'https://www.youtube.com/watch?v=fxg1QRcuPzc'),
  ('Crucifixo inverso no banco inclinado', 'https://www.youtube.com/watch?v=neiVTL2U5Qo'),
  ('Crucifixo inverso no cabo', 'https://www.youtube.com/watch?v=eL5XWNigpvw'),
  ('Crucifixo inverso sentado com halteres', 'https://www.youtube.com/watch?v=OJNdf94tBRM'),
  ('Crucifixo inverso unilateral no cabo', 'https://www.youtube.com/watch?v=oVHf-2RTJm0'),
  ('Cuban press', 'https://www.youtube.com/watch?v=JButGBp_KWo'),
  ('Desenvolvimento Arnold', 'https://www.youtube.com/watch?v=yhJWRlfpEuk')
) as v(nome, url)
where c.name = v.nome;
